# Generated by Django 2.2.7 on 2024-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241202_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=250, verbose_name='Who I am:'),
        ),
    ]
