# Generated by Django 2.2.7 on 2024-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20241206_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Specialist_doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متخصص فى ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=30, verbose_name='المحافظه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(default=1, max_length=25, verbose_name='العنوان بالتفصيل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default=1, max_length=50, verbose_name=' phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default=1, max_length=50, verbose_name='عدد ساعات العمل'),
            preserve_default=False,
        ),
    ]
